# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 19:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_seed_classes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='classes',
            field=models.ManyToManyField(
                through='characters.ClassLevel',
                to='classes.Class'),
        ),
        migrations.AddField(
            model_name='character',
            name='created_by',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL),
        ),
    ]
