# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 23:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_create_character_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='owner',
        ),
    ]
