# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 03:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='races.Race'),
        ),
        migrations.DeleteModel(
            name='Race',
        ),
    ]
