# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 17:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('characters', '0002_remove_owner_from_instrumented_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='created_by',
            field=models.ForeignKey(null=True,
                                    on_delete=models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='character',
            name='slug',
            field=models.SlugField(unique=True),
            preserve_default=False,
        ),
    ]
