# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 04:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_create_characterclass_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassLevel',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False,
                    verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False,
                    verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False,
                    verbose_name='modified')),
                ('level', models.IntegerField(default=1)),
                ('character', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='characters.Character')),
                ('character_class', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='characters.CharacterClass')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='character',
            name='classes',
            field=models.ManyToManyField(
                through='characters.ClassLevel',
                to='characters.CharacterClass'),
        ),
    ]
