# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 01:45
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_add_classlevel_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='slug',
            field=autoslug.fields.AutoSlugField(
                editable=False,
                populate_from=b'name', unique=True),
        ),
        migrations.AlterField(
            model_name='characterclass',
            name='slug',
            field=autoslug.fields.AutoSlugField(
                editable=False,
                populate_from=b'name', unique=True),
        ),
    ]
