# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0008_add_ability_score-defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='race',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='characters.Race'
            ),
        ),
    ]
