# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 02:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0009_add_character_race_relation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterclass',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='character',
            name='classes',
            field=models.ManyToManyField(through='characters.ClassLevel', to='classes.Class'),
        ),
        migrations.AlterField(
            model_name='classlevel',
            name='character_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.Class'),
        ),
        migrations.DeleteModel(
            name='CharacterClass',
        ),
    ]
