# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 16:57
from __future__ import unicode_literals

from django.db import migrations

core_races = [
    ('dwarf', 'Dwarf'),
    ('elf', 'Elf'),
    ('gnome', 'Gnome'),
    ('half-elf', 'Half-Elf'),
    ('half-orc', 'Half-Orc'),
    ('halfling', 'Halfling'),
    ('human', 'Human'),
]


def add_races(apps, schema_editor):
    Race = apps.get_model("characters", "Race")
    for slug, name in core_races:
        race = Race.objects.create(slug=slug, name=name)
        race.save()


def remove_races(apps, schema_editor):
    Race = apps.get_model("characters", "Race")
    for slug, _ in core_races:
        race = Race.objects.get(slug=slug)
        race.delete()


core_classes = [
    ('barbarian', 'Barbarian'),
    ('bard', 'Bard'),
    ('cleric', 'Cleric'),
    ('druid', 'Druid'),
    ('fighter', 'Fighter'),
    ('monk', 'Monk'),
    ('paladin', 'Paladin'),
    ('ranger', 'Ranger'),
    ('rogue', 'Rogue'),
    ('sorcerer', 'Sorcerer'),
    ('wizard', 'Wizard')
]


def add_classes(apps, schema_editor):
    Class = apps.get_model("characters", "CharacterClass")
    for slug, name in core_classes:
        c_class = Class.objects.create(slug=slug, name=name)
        c_class.save()


def remove_classes(apps, schema_editor):
    Class = apps.get_model("characters", "CharacterClass")
    for slug, _ in core_classes:
        c_class = Class.objects.get(slug=slug)
        c_class.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0009_add_character_race_relation'),
    ]

    operations = [
        migrations.RunPython(add_races, reverse_code=remove_races),
        migrations.RunPython(add_classes, reverse_code=remove_classes)
    ]
