#! /bin/bash

base_command='python pathman/manage.py'
command="$base_command flush"
$command

echo "Re-creating the root super user. Choose a password please."
command="$base_command createsuperuser --username root --email root@localhost"
$command

echo "Loading core classes"
command="$base_command loaddata pathman/characters/fixtures/core_classes.json"
