#! /bin/bash

manage_path='pathman/manage.py'
command="migrate"

if [ "$1" ]; then
  if [ "$2" ]; then
    command="$command $1 $2"
  else
    command="$command characters $1"
  fi
fi

python $manage_path $command
