# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 02:22
from __future__ import unicode_literals, print_function

from django.db import migrations
import sys


def info(*objs):
    print("INFO: ", *objs, file=sys.stderr)


core_classes = [
    ('barbarian', 'Barbarian'),
    ('bard', 'Bard'),
    ('cleric', 'Cleric'),
    ('druid', 'Druid'),
    ('fighter', 'Fighter'),
    ('monk', 'Monk'),
    ('paladin', 'Paladin'),
    ('ranger', 'Ranger'),
    ('rogue', 'Rogue'),
    ('sorcerer', 'Sorcerer'),
    ('wizard', 'Wizard')
]


def add_classes(apps, schema_editor):
    Class = apps.get_model("classes", "Class")
    for slug, name in core_classes:
        c_class = Class.objects.create(slug=slug, name=name)
        c_class.save()


def remove_classes(apps, schema_editor):
    Class = apps.get_model("classes", "Class")
    for c_class in Class.objects.all():
        c_class.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_classes, reverse_code=remove_classes)
    ]
