# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 16:57
from __future__ import unicode_literals, print_function

from django.db import migrations
import sys


def info(*objs):
    print("INFO: ", *objs, file=sys.stderr)


core_races = [
    ('dwarf', 'Dwarf'),
    ('elf', 'Elf'),
    ('gnome', 'Gnome'),
    ('half-elf', 'Half-Elf'),
    ('half-orc', 'Half-Orc'),
    ('halfling', 'Halfling'),
    ('human', 'Human'),
]


def add_races(apps, schema_editor):
    Race = apps.get_model("races", "Race")
    for slug, name in core_races:
        race = Race.objects.create(slug=slug, name=name)
        race.save()


def remove_races(apps, schema_editor):
    Race = apps.get_model("races", "Race")
    for slug, _ in core_races:
        try:
            race = Race.objects.get(slug=slug)
            race.delete()
        except:
            info("race '{}' does not exist.".format(slug))


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_races, reverse_code=remove_races),
    ]
